
include Makefile
OBJS = lib_comms.o lib_bilbao.o  lib_chrct.o invreal33.o invmati.o

OFLAG = 

OBJSLIB = irrep_ssg.o

LIBRARY = libIRSSG.a

libs: $(LIBRARY)

$(LIBRARY) : $(OBJS) $(OBJSLIB)
	$(AR) $(ARFLAGS) $(LIBRARY) $(OBJSLIB) $(OBJS)

$(OBJS):%.o:%.f90
	$(F90) -c $(FLAGS) -DIRVSPDATA $*.f90

$(OBJSLIB):%.o:%.f90
	$(F90) -c $(OFLAG) $(FLAGS)  $*.f90 
